### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by kBashar** [FreeFromBorders/f2b_website#1]
Can we rename the repository? IMHO just "website" doesn't hold much context. I think if some prefix is added with "website" it would more self explaining e.g. ffb_site, ffb_website.

**Comment by d34th4ck3r** [comment]
Sure! I like ffb_website or f2b_website, you can choose either of them and make the commit. But once decided, we should stick to same nomenclature throughout the organization.

I'll add you the contributors list right away!
